Setup package, test CI pipeline.
SciML/FastSolvers.jl pull request #2
Opened 2024-06-19 15:49 UTC by dynamic-queries

## Checklist

- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

2024-06-20 15:42 UTC, thazhemadam requested changes

2024-06-20 15:42 UTC, thazhemadam commented on Project.toml
Dependencies must have compats specified.

2024-06-27 11:05 UTC, dynamic-queries commented on Project.toml
Hi compats are now in the respective .tomls .

2024-07-01 12:43 UTC, thazhemadam approved these changes

2024-07-01 12:46 UTC, merged